/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 untitled.glb -- transform
*/

import React from 'react'
import { Center, useGLTF } from '@react-three/drei'

const glbfilename = '/64190f2f0e8619dd68e8100d/64190f2f0e8619dd68e8100d.glb';

const DC3DI_64190f2f0e8619dd68e8100d = (props) => {  
  const { nodes, materials } = useGLTF(glbfilename)
  return (
    <Center>
      <group {...props} dispose={null}>
        <group scale={0.05}>
          <mesh geometry={nodes.Mesh002.geometry} material={materials.FABRIC_2_FRONT_TOP} />
          <mesh geometry={nodes.Mesh002_1.geometry} material={materials['FABRIC_1_FRONT_SKIRT.001']} />
          <mesh geometry={nodes.Mesh002_2.geometry} material={materials.FABRIC_4_FRONT_BELT} />
          <mesh geometry={nodes.Mesh002_3.geometry} material={materials.FABRIC_4_FRONT_BELT} />
          <mesh geometry={nodes.Mesh002_4.geometry} material={materials.FABRIC_2_FRONT_TOP} />
        </group>
      </group>
    </Center>
  )
}

useGLTF.preload(glbfilename);
export default DC3DI_64190f2f0e8619dd68e8100d;