/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 .\\untitled.glb --transform
*/

import React from 'react'
import { useGLTF, Center } from '@react-three/drei'

const glbfilename = '/6418a4e0e8683d4616405b43/6418a4e0e8683d4616405b43.glb';
const DC3DI_6418a4e0e8683d4616405b43 = (props) => {

  const { nodes, materials } = useGLTF(glbfilename)
  return (
    <Center>
      <group {...props} dispose={null}>
        <group scale={0.035}>
          <mesh geometry={nodes.Mesh024.geometry} material={materials.FABRIC_2_FRONT_SHIRT} />
          <mesh geometry={nodes.Mesh024_1.geometry} material={materials.FABRIC_1_FRONT_SKIRT} />
          <mesh geometry={nodes.Mesh024_2.geometry} material={materials.FABRIC_6_FRONT_COLLAR} />
          <mesh geometry={nodes.Mesh024_3.geometry} material={materials.FABRIC_6_FRONT_COLLAR} />
          <mesh geometry={nodes.Mesh024_4.geometry} material={materials.FABRIC_6_FRONT_COLLAR} />
          <mesh geometry={nodes.Mesh024_5.geometry} material={materials.FABRIC_6_FRONT_COLLAR} />
          <mesh geometry={nodes.Mesh024_6.geometry} material={materials.FABRIC_6_FRONT_COLLAR} />
          <mesh geometry={nodes.Mesh024_7.geometry} material={materials.FABRIC_6_FRONT_COLLAR} />
        </group>
      </group>
    </Center>
  )
}

useGLTF.preload(glbfilename)
export default DC3DI_6418a4e0e8683d4616405b43;