/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 .\\woman-dress-02.glb --transform
*/

import React from "react";
import { useGLTF, Center } from "@react-three/drei";

const glbfilename = '/641867251e5bdbd48e5780d5/641867251e5bdbd48e5780d5.glb';

const DC3DI_641867251e5bdbd48e5780d5 = (props) => {  
  const { nodes, materials } = useGLTF(glbfilename);
  return (
    <Center>
      <group {...props} dispose={null}>
        <group scale={0.05}>
          <mesh
            geometry={nodes.Mesh001.geometry}
            material={materials["FABRIC_2_FRONT_4773.001"]}
          />
          <mesh
            geometry={nodes.Mesh001_1.geometry}
            material={materials["FABRIC_1_FRONT_4768.001"]}
          />
          <mesh
            geometry={nodes.Mesh001_2.geometry}
            material={materials.FABRIC_4_FRONT_4783}
          />
          <mesh
            geometry={nodes.Mesh001_3.geometry}
            material={materials.FABRIC_3_FRONT_4778}
          />
          <mesh
            geometry={nodes.Mesh001_4.geometry}
            material={materials.FABRIC_3_FRONT_4778}
          />
        </group>
      </group>
    </Center>
  );
};

useGLTF.preload(glbfilename);
export default DC3DI_641867251e5bdbd48e5780d5;
