/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 mensuit.glb --transform
*/

import React, { useRef } from 'react'
import { useGLTF, Center } from '@react-three/drei'

const glbfilename = '/64427d3ea3f6900eda455cda/64427d3ea3f6900eda455cda.glb';
const DC3DI_64427d3ea3f6900eda455cda = (props) => {
  const { nodes, materials } = useGLTF(glbfilename)
  return (
    <Center>
      <group {...props} dispose={null}>
        <group scale={0.04}>
          <mesh geometry={nodes.Mesh.geometry} material={materials.FABRIC_1_FRONT_4672} />
          <mesh geometry={nodes.Mesh_1.geometry} material={materials.PT_FABRIC_FRONT_4921} />
          <mesh geometry={nodes.Mesh_2.geometry} material={materials.Material1237100} />
        </group>
        <group scale={0.04}>
          <mesh geometry={nodes.Mesh001.geometry} material={materials['G1-PI-02_FABRIC_1_FRONT_4667']} />
          <mesh geometry={nodes.Mesh001_1.geometry} material={materials['G1-PI-02_FABRIC_1_FRONT_4667']} />
          <mesh geometry={nodes.Mesh001_2.geometry} material={materials['G1-PI-02_FABRIC_1_FRONT_4667']} />
        </group>
        <group scale={0.04}>
          <mesh geometry={nodes.Mesh002.geometry} material={materials.FABRIC_1_FRONT_4672} />
          <mesh geometry={nodes.Mesh002_1.geometry} material={materials.FABRIC_1_FRONT_4672} />
          <mesh geometry={nodes.Mesh002_2.geometry} material={materials['G1-PI-02_FABRIC_1_FRONT_4667']} />
        </group>
        <group scale={0.04}>
          <mesh geometry={nodes.Mesh003.geometry} material={materials.FABRIC_1_FRONT_4672} />
          <mesh geometry={nodes.Mesh003_1.geometry} material={materials.FABRIC_1_FRONT_4672} />
          <mesh geometry={nodes.Mesh003_2.geometry} material={materials['G1-PI-02_FABRIC_1_FRONT_4667']} />
        </group>
        <mesh geometry={nodes.Object001.geometry} material={materials.Material1221501} scale={0.04} />
        <group scale={0.04}>
          <mesh geometry={nodes.Mesh007.geometry} material={materials.Fabric1055985_FRONT_30657} />
          <mesh geometry={nodes.Mesh007_1.geometry} material={materials.Material1237100} />
          <mesh geometry={nodes.Mesh007_2.geometry} material={materials['G1-PI-02_FABRIC_1_FRONT_4667']} />
        </group>
        <mesh geometry={nodes.Object003.geometry} material={materials['G1-PI-02_FABRIC_1_FRONT_4667']} scale={0.04} />
        <group scale={0.04}>
          <mesh geometry={nodes.Mesh010.geometry} material={materials['G1-PI-02_FABRIC_1_FRONT_4667']} />
          <mesh geometry={nodes.Mesh010_1.geometry} material={materials['G1-PI-02_FABRIC_1_FRONT_4667']} />
        </group>
        <group scale={0.04}>
          <mesh geometry={nodes.Mesh011.geometry} material={materials['G1-PI-02_FABRIC_1_FRONT_4667']} />
          <mesh geometry={nodes.Mesh011_1.geometry} material={materials['G1-PI-02_FABRIC_1_FRONT_4667']} />
        </group>
      </group>
    </Center>
  )
}

useGLTF.preload(glbfilename)
export default DC3DI_64427d3ea3f6900eda455cda;