/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 untitled.glb --transform
*/

import React from 'react'
import { useGLTF, Center } from '@react-three/drei'

const glbfilename = '/641910470e8619dd68e8100f/641910470e8619dd68e8100f.glb';
const DC3DI_641910470e8619dd68e8100f = (props) => {
  const { nodes, materials } = useGLTF(glbfilename)
  return (
    <Center>
      <group {...props} dispose={null}>
        <mesh geometry={nodes.Object002.geometry} material={materials['Material5037.top']} position={[0.05, 0, 0.04]} scale={0.04} />
        <mesh geometry={nodes.Object001.geometry} material={materials['Material5037.bottom']} position={[0.05, 0, 0.04]} scale={0.04} />
        <mesh geometry={nodes.Object003.geometry} material={materials['Material #5.cap']} position={[0.05, 0, 0.04]} scale={0.04} />
        <group position={[0.05, 0, 0.04]} scale={0.04}>
          <mesh geometry={nodes.Mesh003.geometry} material={materials['Material5037.bottom']} />
          <mesh geometry={nodes.Mesh003_1.geometry} material={materials.Material3799} />
        </group>
        <mesh geometry={nodes.Object004.geometry} material={materials.Material3799} position={[0.05, 0, 0.04]} scale={0.04} />
        <mesh geometry={nodes['M-obj1'].geometry} material={materials['Material5037.top']} position={[0.05, 0, 0.04]} scale={0.04} />
      </group>
    </Center>
  )
}

useGLTF.preload(glbfilename)
export default DC3DI_641910470e8619dd68e8100f;